// <auto-generated />
namespace PowerJump.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_validation_to_Project_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_validation_to_Project_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201610311549414_add_validation_to_Project_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
