// <auto-generated />
namespace PowerJump.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class import_db_Gallery_Event_Project : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(import_db_Gallery_Event_Project));
        
        string IMigrationMetadata.Id
        {
            get { return "201610242108423_import_db_Gallery_Event_Project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
